name: Auto Liqi

on:
    workflow_dispatch:
jobs:
    auto-liqi:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5

            - name: Install requests
              run: python -m pip install --upgrade pip install requests

            - name: Set up Node.js
              uses: actions/setup-node@v4

            - name: Install protobufjs and protobufjs-cli
              run: npm install -g protobufjs protobufjs-cli
            
            - name: Run get_liqi.py
              run: python get_liqi.py

            - name: Generate liqi.proto from liqi.json
              run: pbjs -t proto3 liqi.json > liqi.proto

            - name: Generate liqi_pb2.py from liqi.proto
              run: protoc --python_out=. liqi.proto

            - name: Publish protobuf files
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.version }}
                path: |
                  liqi.proto
                  liqi_pb2.py
                  




